apiVersion: v1
kind: Service
metadata:
  name: gpstracker-backend
  namespace: gpstracker
  labels:
    app: gpstracker-backend
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 5050
    targetPort: 5050
    protocol: TCP
    name: http
  selector:
    app: gpstracker-backend
