apiVersion: v1
kind: Service
metadata:
  name: gpstracker-app
  namespace: gpstracker
  labels:
    app: gpstracker-app
    component: application
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 5050
    targetPort: 5050
    protocol: TCP
    name: backend
  selector:
    app: gpstracker-app
